name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check
        run: deno task check

      - uses: akiraohgaki/actions/git-commit-push@main

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build
        run: deno task build

      - uses: akiraohgaki/actions/git-commit-push@main

  test:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1.4

      - name: Test
        run: deno task test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-report
          path: |
            coverage/
            playwright-report/
          retention-days: 30
